// Inserisci qui il numero WhatsApp completo di prefisso internazionale,
// senza +, spazi o trattini. Esempio Svizzera: 41791234567
const PHONE = '41790000000';

const translations = {
  it: {
    pageTitle:'Les Diablerets Panorama', metaDescription:'Les Diablerets Panorama: appartamento privato di 44 m² con terrazza di 12 m², vista sul ghiacciaio e sulle piste.',
    navApartment:'Appartamento',navLocation:'Posizione',navActivities:'Sport & relax',checkAvailability:'Disponibilità',heroEyebrow:'Appartamento privato · Les Diablerets',heroLead:'44 m² con terrazza di 12 m², vista sul ghiacciaio e sulle piste. Tutto ciò che serve è raggiungibile a piedi.',discover:"Scopri l'appartamento",writeWhatsapp:'Scrivi su WhatsApp',statApartment:'m² appartamento',statTerrace:'m² terrazza',statSlopes:'min dalle piste',statShops:'min dai servizi',
    apartmentEyebrow:"L'appartamento",apartmentTitle:'Compatto, luminoso<br>e ben posizionato.',apartmentText1:'Les Diablerets Panorama è un appartamento di 44 m² con una terrazza privata di 12 m² e una vista aperta sul ghiacciaio e sulle piste da sci.',apartmentText2:"È una base pratica per chi vuole alternare sport, passeggiate e momenti di riposo, senza dipendere dall'auto durante il soggiorno.",photoView:'Vista sul ghiacciaio e sulle piste',photoTerrace:'Terrazza privata di 12 m²',photoInterior:'Spazi semplici e funzionali',
    locationEyebrow:'Posizione',locationTitle:'Tutto vicino.<br>Davvero.',shopsTitle:'Servizi quotidiani',shopsText:'Supermercati, panetterie, banca e ristoranti.',sportTitle:'Piscina, tennis e pattinaggio',sportText:'Piscina e tennis in estate, pista di pattinaggio in inverno.',slopesTitle:'Piste da sci',slopesText:'Impianti e piste raggiungibili comodamente a piedi.',stationTitle:'Stazione ferroviaria',stationText:'Collegamenti pratici per arrivare senza automobile.',
    activitiesEyebrow:'Sport & relax',activitiesTitle:'Una base per muoversi.<br>Un posto per recuperare.',winterLabel:'Inverno',winterTitle:'Sci e pattinaggio',winterText:'Le attività principali del villaggio sono a pochi minuti a piedi.',summerLabel:'Estate',summerTitle:'Tennis, piscina ed escursioni',summerText:'Una giornata attiva può iniziare direttamente dalla porta di casa.',saunaTitle:"Sauna nell'immobile",gymTitle:"Palestra nell'immobile",wellnessText:"Due servizi utili per rilassarsi o allenarsi senza uscire dall'edificio.",
    contactEyebrow:'Per organizzare un soggiorno',contactTitle:'Date, disponibilità<br>e informazioni pratiche.',contactText:'Scrivimi direttamente su WhatsApp. Ti risponderò con disponibilità e dettagli.',openWhatsapp:'Apri WhatsApp',footerText:'Appartamento privato condiviso con amici e conoscenti.',privateSite:'Sito privato non indicizzato',mobileWhatsapp:'WhatsApp',whatsappAvailability:"Ciao! Vorrei sapere se Les Diablerets Panorama è disponibile e ricevere qualche informazione pratica."
  },
  fr: {
    pageTitle:'Les Diablerets Panorama', metaDescription:'Les Diablerets Panorama : appartement privé de 44 m² avec terrasse de 12 m², vue sur le glacier et les pistes.',
    navApartment:'Appartement',navLocation:'Situation',navActivities:'Sport & détente',checkAvailability:'Disponibilités',heroEyebrow:'Appartement privé · Les Diablerets',heroLead:'44 m² avec une terrasse de 12 m², vue sur le glacier et les pistes. Tout est accessible à pied.',discover:"Découvrir l'appartement",writeWhatsapp:'Écrire sur WhatsApp',statApartment:"m² d'appartement",statTerrace:'m² de terrasse',statSlopes:'min des pistes',statShops:'min des services',
    apartmentEyebrow:"L'appartement",apartmentTitle:'Compact, lumineux<br>et bien situé.',apartmentText1:'Les Diablerets Panorama est un appartement de 44 m² avec une terrasse privée de 12 m² et une vue dégagée sur le glacier et les pistes de ski.',apartmentText2:"C'est une base pratique pour alterner sport, promenades et repos, sans dépendre de la voiture pendant le séjour.",photoView:'Vue sur le glacier et les pistes',photoTerrace:'Terrasse privée de 12 m²',photoInterior:'Des espaces simples et fonctionnels',
    locationEyebrow:'Situation',locationTitle:'Tout est proche.<br>Vraiment.',shopsTitle:'Services quotidiens',shopsText:'Supermarchés, boulangeries, banque et restaurants.',sportTitle:'Piscine, tennis et patinage',sportText:'Piscine et tennis en été, patinoire en hiver.',slopesTitle:'Pistes de ski',slopesText:'Remontées mécaniques et pistes facilement accessibles à pied.',stationTitle:'Gare ferroviaire',stationText:'Des liaisons pratiques pour arriver sans voiture.',
    activitiesEyebrow:'Sport & détente',activitiesTitle:'Un point de départ actif.<br>Un lieu pour récupérer.',winterLabel:'Hiver',winterTitle:'Ski et patinage',winterText:'Les principales activités du village sont à quelques minutes à pied.',summerLabel:'Été',summerTitle:'Tennis, piscine et randonnée',summerText:"Une journée active peut commencer directement depuis l'appartement.",saunaTitle:"Sauna dans l'immeuble",gymTitle:"Salle de sport dans l'immeuble",wellnessText:"Deux équipements utiles pour se détendre ou s'entraîner sans quitter le bâtiment.",
    contactEyebrow:'Pour organiser un séjour',contactTitle:'Dates, disponibilités<br>et informations pratiques.',contactText:'Écrivez-moi directement sur WhatsApp. Je vous répondrai avec les disponibilités et les détails.',openWhatsapp:'Ouvrir WhatsApp',footerText:'Appartement privé partagé avec des amis et des connaissances.',privateSite:'Site privé non indexé',mobileWhatsapp:'WhatsApp',whatsappAvailability:"Bonjour ! J'aimerais savoir si Les Diablerets Panorama est disponible et recevoir quelques informations pratiques."
  },
  en: {
    pageTitle:'Les Diablerets Panorama', metaDescription:'Les Diablerets Panorama: a private 44 m² apartment with a 12 m² terrace overlooking the glacier and ski slopes.',
    navApartment:'Apartment',navLocation:'Location',navActivities:'Sport & relaxation',checkAvailability:'Availability',heroEyebrow:'Private apartment · Les Diablerets',heroLead:'44 m² with a 12 m² terrace overlooking the glacier and ski slopes. Everything you need is within walking distance.',discover:'Discover the apartment',writeWhatsapp:'Message on WhatsApp',statApartment:'m² apartment',statTerrace:'m² terrace',statSlopes:'min to the slopes',statShops:'min to services',
    apartmentEyebrow:'The apartment',apartmentTitle:'Compact, bright<br>and well located.',apartmentText1:'Les Diablerets Panorama is a 44 m² apartment with a private 12 m² terrace and open views over the glacier and ski slopes.',apartmentText2:'It is a practical base for combining sport, walks and downtime without relying on a car during your stay.',photoView:'Views over the glacier and slopes',photoTerrace:'Private 12 m² terrace',photoInterior:'Simple, functional spaces',
    locationEyebrow:'Location',locationTitle:'Everything nearby.<br>Really.',shopsTitle:'Everyday services',shopsText:'Supermarkets, bakeries, a bank and restaurants.',sportTitle:'Swimming, tennis and skating',sportText:'Swimming and tennis in summer, ice skating in winter.',slopesTitle:'Ski slopes',slopesText:'Ski lifts and slopes are an easy walk away.',stationTitle:'Train station',stationText:'Practical connections make it easy to arrive without a car.',
    activitiesEyebrow:'Sport & relaxation',activitiesTitle:'A base for activity.<br>A place to recover.',winterLabel:'Winter',winterTitle:'Skiing and skating',winterText:'The village’s main activities are only a few minutes away on foot.',summerLabel:'Summer',summerTitle:'Tennis, swimming and hiking',summerText:'An active day can start directly from the apartment.',saunaTitle:'Sauna in the building',gymTitle:'Gym in the building',wellnessText:'Two useful amenities for relaxing or training without leaving the building.',
    contactEyebrow:'To arrange a stay',contactTitle:'Dates, availability<br>and practical information.',contactText:'Message me directly on WhatsApp. I will reply with availability and details.',openWhatsapp:'Open WhatsApp',footerText:'A private apartment shared with friends and acquaintances.',privateSite:'Private, non-indexed website',mobileWhatsapp:'WhatsApp',whatsappAvailability:"Hi! I'd like to know whether Les Diablerets Panorama is available and receive some practical information."
  }
};

let currentLang=localStorage.getItem('ldpLang')||(navigator.language||'it').slice(0,2);if(!translations[currentLang])currentLang='it';
function applyLanguage(lang){currentLang=translations[lang]?lang:'it';const t=translations[currentLang];document.documentElement.lang=currentLang;document.title=t.pageTitle;document.querySelector('meta[name="description"]').setAttribute('content',t.metaDescription);document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(t[key])el.textContent=t[key]});document.querySelectorAll('[data-i18n-html]').forEach(el=>{const key=el.dataset.i18nHtml;if(t[key])el.innerHTML=t[key]});document.querySelectorAll('[data-lang]').forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===currentLang));document.querySelectorAll('.js-whatsapp').forEach(link=>{const message=t[link.dataset.messageKey||'whatsappAvailability'];link.href=`https://wa.me/${PHONE}?text=${encodeURIComponent(message)}`;link.target='_blank';link.rel='noopener'});localStorage.setItem('ldpLang',currentLang)}
document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>applyLanguage(btn.dataset.lang)));applyLanguage(currentLang);
document.getElementById('year').textContent=new Date().getFullYear();
const header=document.querySelector('.site-header');window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>40),{passive:true});
const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('.main-nav');menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}else{document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'))}
