// Inserisci qui il numero WhatsApp completo di prefisso internazionale,
// senza +, spazi o trattini. Esempio Svizzera: 41791234567
const PHONE = '41790000000';

const translations = {
  it: {
    pageTitle:'Les Diablerets Panorama', metaDescription:'Les Diablerets Panorama: appartamento privato di 44 m² con terrazza di 12 m², vista sul ghiacciaio e sulle piste.',
    navApartment:'Appartamento',navLocation:'Posizione',navActivities:'Sport & relax',checkAvailability:'Disponibilità',heroEyebrow:'Appartamento privato · Les Diablerets',heroLead:'Un appartamento luminoso con terrazza e una vista aperta sul ghiacciaio e sulle piste: il punto di partenza ideale per vivere Les Diablerets tra sport, aria di montagna e momenti di relax.',discover:"Scopri l'appartamento",writeWhatsapp:'Scrivi su WhatsApp',statApartment:'m² appartamento',statTerrace:'m² terrazza',statSlopes:'min dalle piste',statShops:'min dai servizi',
    apartmentEyebrow:"L'appartamento",apartmentTitle:'Compatto, luminoso<br>e ben posizionato.',apartmentText1:'Les Diablerets Panorama è un appartamento di 44 m² con una terrazza privata di 12 m² e una vista aperta sul ghiacciaio e sulle piste da sci.',apartmentText2:"È una base pratica per chi vuole alternare sport, passeggiate e momenti di riposo, senza dipendere dall'auto durante il soggiorno.",photoView:'Vista sul ghiacciaio e sulle piste',photoTerrace:'Terrazza privata di 12 m²',photoInterior:'Spazi semplici e funzionali',
    locationEyebrow:'Posizione',locationTitle:'Tutto vicino.<br>Davvero.',shopsTitle:'Servizi quotidiani',shopsText:'Supermercati, panetterie, banca e ristoranti.',sportTitle:'Piscina, tennis e pattinaggio',sportText:'Piscina e tennis in estate, pista di pattinaggio in inverno.',slopesTitle:'Piste da sci',slopesText:'Impianti e piste raggiungibili comodamente a piedi.',stationTitle:'Stazione ferroviaria',stationText:'Collegamenti pratici per arrivare senza automobile.',gstaadTitle:'Gstaad',gstaadText:'Una delle località alpine più note della regione è raggiungibile in circa 25 minuti di auto.',
    activitiesEyebrow:'Sport & relax',activitiesTitle:'Una base per muoversi.<br>Un posto per recuperare.',winterLabel:'Inverno',winterTitle:'Sci, neve e benessere',winterText:'Sci, pattinaggio, bob e passeggiate con le ciaspole. Per una pausa di benessere, i Bains de Lavey sono a circa 30 minuti di auto.',summerLabel:'Estate',summerTitle:'Montagna in movimento',summerText:'Escursioni, mountain bike, bici, arrampicata, parapendio, tennis e piscina: molte attività iniziano direttamente dal villaggio.',glacierTitle:'Glacier 3000 e Peak Walk by Tissot',glacierText:'In estate e in inverno, una visita al ghiacciaio e al ponte sospeso tra due vette è una delle esperienze più caratteristiche della zona.',saunaTitle:"Sauna nell'immobile",gymTitle:"Palestra nell'immobile",wellnessText:"Due servizi utili per rilassarsi o allenarsi senza uscire dall'edificio.",
    contactEyebrow:'Per organizzare un soggiorno',contactTitle:'Date, disponibilità<br>e informazioni pratiche.',contactText:'Scrivimi direttamente su WhatsApp. Ti risponderò con disponibilità e dettagli.',openWhatsapp:'Apri WhatsApp',footerText:'Appartamento privato condiviso con amici e conoscenti.',privateSite:'Sito privato non indicizzato',mobileWhatsapp:'WhatsApp',whatsappAvailability:"Ciao! Vorrei sapere se Les Diablerets Panorama è disponibile e ricevere qualche informazione pratica."
  },
  fr: {
    pageTitle:'Les Diablerets Panorama', metaDescription:'Les Diablerets Panorama : appartement privé de 44 m² avec terrasse de 12 m², vue sur le glacier et les pistes.',
    navApartment:'Appartement',navLocation:'Situation',navActivities:'Sport & détente',checkAvailability:'Disponibilités',heroEyebrow:'Appartement privé · Les Diablerets',heroLead:'Un appartement lumineux avec terrasse et une vue dégagée sur le glacier et les pistes : un point de départ idéal pour profiter des Diablerets entre sport, air de montagne et détente.',discover:"Découvrir l'appartement",writeWhatsapp:'Écrire sur WhatsApp',statApartment:"m² d'appartement",statTerrace:'m² de terrasse',statSlopes:'min des pistes',statShops:'min des services',
    apartmentEyebrow:"L'appartement",apartmentTitle:'Compact, lumineux<br>et bien situé.',apartmentText1:'Les Diablerets Panorama est un appartement de 44 m² avec une terrasse privée de 12 m² et une vue dégagée sur le glacier et les pistes de ski.',apartmentText2:"C'est une base pratique pour alterner sport, promenades et repos, sans dépendre de la voiture pendant le séjour.",photoView:'Vue sur le glacier et les pistes',photoTerrace:'Terrasse privée de 12 m²',photoInterior:'Des espaces simples et fonctionnels',
    locationEyebrow:'Situation',locationTitle:'Tout est proche.<br>Vraiment.',shopsTitle:'Services quotidiens',shopsText:'Supermarchés, boulangeries, banque et restaurants.',sportTitle:'Piscine, tennis et patinage',sportText:'Piscine et tennis en été, patinoire en hiver.',slopesTitle:'Pistes de ski',slopesText:'Remontées mécaniques et pistes facilement accessibles à pied.',stationTitle:'Gare ferroviaire',stationText:'Des liaisons pratiques pour arriver sans voiture.',gstaadTitle:'Gstaad',gstaadText:'L’une des stations alpines les plus connues de la région se trouve à environ 25 minutes en voiture.',
    activitiesEyebrow:'Sport & détente',activitiesTitle:'Un point de départ actif.<br>Un lieu pour récupérer.',winterLabel:'Hiver',winterTitle:'Ski, neige et bien-être',winterText:'Ski, patinage, luge et balades en raquettes. Pour une pause bien-être, les Bains de Lavey sont à environ 30 minutes en voiture.',summerLabel:'Été',summerTitle:'La montagne en mouvement',summerText:'Randonnée, VTT, vélo, escalade, parapente, tennis et piscine : de nombreuses activités commencent directement au village.',glacierTitle:'Glacier 3000 et Peak Walk by Tissot',glacierText:'En été comme en hiver, la visite du glacier et du pont suspendu reliant deux sommets est l’une des expériences emblématiques de la région.',saunaTitle:"Sauna dans l'immeuble",gymTitle:"Salle de sport dans l'immeuble",wellnessText:"Deux équipements utiles pour se détendre ou s'entraîner sans quitter le bâtiment.",
    contactEyebrow:'Pour organiser un séjour',contactTitle:'Dates, disponibilités<br>et informations pratiques.',contactText:'Écrivez-moi directement sur WhatsApp. Je vous répondrai avec les disponibilités et les détails.',openWhatsapp:'Ouvrir WhatsApp',footerText:'Appartement privé partagé avec des amis et des connaissances.',privateSite:'Site privé non indexé',mobileWhatsapp:'WhatsApp',whatsappAvailability:"Bonjour ! J'aimerais savoir si Les Diablerets Panorama est disponible et recevoir quelques informations pratiques."
  },
  en: {
    pageTitle:'Les Diablerets Panorama', metaDescription:'Les Diablerets Panorama: a private 44 m² apartment with a 12 m² terrace overlooking the glacier and ski slopes.',
    navApartment:'Apartment',navLocation:'Location',navActivities:'Sport & relaxation',checkAvailability:'Availability',heroEyebrow:'Private apartment · Les Diablerets',heroLead:'A bright apartment with a terrace and open views of the glacier and ski slopes: an ideal base for enjoying Les Diablerets through sport, mountain air and downtime.',discover:'Discover the apartment',writeWhatsapp:'Message on WhatsApp',statApartment:'m² apartment',statTerrace:'m² terrace',statSlopes:'min to the slopes',statShops:'min to services',
    apartmentEyebrow:'The apartment',apartmentTitle:'Compact, bright<br>and well located.',apartmentText1:'Les Diablerets Panorama is a 44 m² apartment with a private 12 m² terrace and open views over the glacier and ski slopes.',apartmentText2:'It is a practical base for combining sport, walks and downtime without relying on a car during your stay.',photoView:'Views over the glacier and slopes',photoTerrace:'Private 12 m² terrace',photoInterior:'Simple, functional spaces',
    locationEyebrow:'Location',locationTitle:'Everything nearby.<br>Really.',shopsTitle:'Everyday services',shopsText:'Supermarkets, bakeries, a bank and restaurants.',sportTitle:'Swimming, tennis and skating',sportText:'Swimming and tennis in summer, ice skating in winter.',slopesTitle:'Ski slopes',slopesText:'Ski lifts and slopes are an easy walk away.',stationTitle:'Train station',stationText:'Practical connections make it easy to arrive without a car.',gstaadTitle:'Gstaad',gstaadText:'One of the region’s best-known Alpine destinations is around 25 minutes away by car.',
    activitiesEyebrow:'Sport & relaxation',activitiesTitle:'A base for activity.<br>A place to recover.',winterLabel:'Winter',winterTitle:'Snow, sport and wellness',winterText:'Skiing, ice skating, sledging and snowshoe walks. For a wellness break, Les Bains de Lavey are around 30 minutes away by car.',summerLabel:'Summer',summerTitle:'The mountain in motion',summerText:'Hiking, mountain biking, cycling, climbing, paragliding, tennis and swimming: many activities begin right in the village.',glacierTitle:'Glacier 3000 and Peak Walk by Tissot',glacierText:'In both summer and winter, visiting the glacier and the suspension bridge linking two peaks is one of the area’s signature experiences.',saunaTitle:'Sauna in the building',gymTitle:'Gym in the building',wellnessText:'Two useful amenities for relaxing or training without leaving the building.',
    contactEyebrow:'To arrange a stay',contactTitle:'Dates, availability<br>and practical information.',contactText:'Message me directly on WhatsApp. I will reply with availability and details.',openWhatsapp:'Open WhatsApp',footerText:'A private apartment shared with friends and acquaintances.',privateSite:'Private, non-indexed website',mobileWhatsapp:'WhatsApp',whatsappAvailability:"Hi! I'd like to know whether Les Diablerets Panorama is available and receive some practical information."
  }
};


Object.assign(translations.it,{
  navAvailability:'Disponibilità & prezzi',checkDates:'Controlla date e prezzi',exploreDiablerets:'Esplora Les Diablerets',exploreGlacier:'Scopri Glacier 3000',availabilityEyebrow:'Disponibilità & prezzi',availabilityTitle:'Scegli le date.<br>Calcola il soggiorno.',availabilityText:'Seleziona arrivo e partenza nel calendario. Il prezzo è indicativo e la prenotazione viene confermata personalmente via WhatsApp.',lowSeason:'notte · bassa stagione',highSeason:'notte · alta stagione',cleaningFee:'pulizia finale',available:'Disponibile',selected:'Selezionato',unavailable:'Non disponibile',yourStay:'Il tuo soggiorno',arrival:'Arrivo',departure:'Partenza',nights:'Notti',stayPrice:'Soggiorno',cleaning:'Pulizia finale',estimatedTotal:'Totale indicativo',quoteNote:'Soggiorno minimo: 2 notti. Disponibilità e prezzo finale da confermare.',requestBooking:'Richiedi la prenotazione',resetDates:'Cancella le date'
});
Object.assign(translations.fr,{
  navAvailability:'Disponibilités & tarifs',checkDates:'Voir les dates et tarifs',exploreDiablerets:'Explorer Les Diablerets',exploreGlacier:'Découvrir Glacier 3000',availabilityEyebrow:'Disponibilités & tarifs',availabilityTitle:'Choisissez vos dates.<br>Estimez le séjour.',availabilityText:'Sélectionnez votre arrivée et votre départ. Le tarif est indicatif et la réservation est confirmée personnellement sur WhatsApp.',lowSeason:'nuit · basse saison',highSeason:'nuit · haute saison',cleaningFee:'nettoyage final',available:'Disponible',selected:'Sélectionné',unavailable:'Indisponible',yourStay:'Votre séjour',arrival:'Arrivée',departure:'Départ',nights:'Nuits',stayPrice:'Séjour',cleaning:'Nettoyage final',estimatedTotal:'Total indicatif',quoteNote:'Séjour minimum : 2 nuits. Disponibilité et tarif final à confirmer.',requestBooking:'Demander la réservation',resetDates:'Effacer les dates'
});
Object.assign(translations.en,{
  navAvailability:'Availability & rates',checkDates:'Check dates and rates',exploreDiablerets:'Explore Les Diablerets',exploreGlacier:'Discover Glacier 3000',availabilityEyebrow:'Availability & rates',availabilityTitle:'Choose your dates.<br>Estimate your stay.',availabilityText:'Select arrival and departure in the calendar. The price is indicative and the booking is personally confirmed through WhatsApp.',lowSeason:'night · low season',highSeason:'night · high season',cleaningFee:'final cleaning',available:'Available',selected:'Selected',unavailable:'Unavailable',yourStay:'Your stay',arrival:'Arrival',departure:'Departure',nights:'Nights',stayPrice:'Stay',cleaning:'Final cleaning',estimatedTotal:'Estimated total',quoteNote:'Minimum stay: 2 nights. Availability and final price must be confirmed.',requestBooking:'Request booking',resetDates:'Clear dates'
});

let currentLang=localStorage.getItem('ldpLang')||(navigator.language||'it').slice(0,2);if(!translations[currentLang])currentLang='it';
function applyLanguage(lang){currentLang=translations[lang]?lang:'it';const t=translations[currentLang];document.documentElement.lang=currentLang;document.title=t.pageTitle;document.querySelector('meta[name="description"]').setAttribute('content',t.metaDescription);document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n;if(t[key])el.textContent=t[key]});document.querySelectorAll('[data-i18n-html]').forEach(el=>{const key=el.dataset.i18nHtml;if(t[key])el.innerHTML=t[key]});document.querySelectorAll('[data-lang]').forEach(btn=>btn.classList.toggle('active',btn.dataset.lang===currentLang));document.querySelectorAll('.js-whatsapp').forEach(link=>{const message=t[link.dataset.messageKey||'whatsappAvailability'];link.href=`https://wa.me/${PHONE}?text=${encodeURIComponent(message)}`;link.target='_blank';link.rel='noopener'});localStorage.setItem('ldpLang',currentLang);if(window.renderBookingCalendar)window.renderBookingCalendar()}
document.querySelectorAll('[data-lang]').forEach(btn=>btn.addEventListener('click',()=>applyLanguage(btn.dataset.lang)));applyLanguage(currentLang);
document.getElementById('year').textContent=new Date().getFullYear();
const header=document.querySelector('.site-header');window.addEventListener('scroll',()=>header.classList.toggle('scrolled',window.scrollY>40),{passive:true});
const menuButton=document.querySelector('.menu-toggle');const nav=document.querySelector('.main-nav');menuButton.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menuButton.setAttribute('aria-expanded','false')}));
if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}else{document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'))}


// Calendario e preventivo: funziona interamente su GitHub Pages, senza server.
const cfg=window.BOOKING_CONFIG||{currency:'CHF',cleaningFee:90,minimumNights:2,rates:[{months:[1,2,3,4,5,6,7,8,9,10,11,12],nightly:150}],unavailableRanges:[]};
let calendarMonth=new Date();calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth(),1);
let arrivalDate=null,departureDate=null;
const iso=d=>{const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`};
const fromIso=x=>{const [y,m,d]=x.split('-').map(Number);return new Date(y,m-1,d)};
const dayStart=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate());
const isUnavailable=d=>(cfg.unavailableRanges||[]).some(r=>d>=fromIso(r.start)&&d<=fromIso(r.end));
const rateFor=d=>{const month=d.getMonth()+1;const rate=(cfg.rates||[]).find(r=>r.months.includes(month));return rate?rate.nightly:0};
const locale=()=>currentLang==='fr'?'fr-CH':currentLang==='en'?'en-GB':'it-CH';
const money=n=>`${cfg.currency} ${Math.round(n).toLocaleString(locale())}`;
function rangeIsFree(a,b){for(let d=new Date(a);d<b;d.setDate(d.getDate()+1)){if(isUnavailable(d))return false}return true}
function selectCalendarDate(d){
  if(!arrivalDate||departureDate||d<arrivalDate){arrivalDate=d;departureDate=null}
  else if(d>arrivalDate){if(rangeIsFree(arrivalDate,d)){departureDate=d}else{arrivalDate=d;departureDate=null}}
  renderBookingCalendar();
}
function bookingMessage(){
 const t=translations[currentLang];
 if(!arrivalDate||!departureDate)return t.whatsappAvailability;
 const nights=Math.round((departureDate-arrivalDate)/86400000);let stay=0;for(let d=new Date(arrivalDate);d<departureDate;d.setDate(d.getDate()+1))stay+=rateFor(d);
 const dateFmt=d=>d.toLocaleDateString(locale(),{day:'2-digit',month:'long',year:'numeric'});
 if(currentLang==='fr')return `Bonjour ! Je souhaite demander le séjour aux Diablerets du ${dateFmt(arrivalDate)} au ${dateFmt(departureDate)} (${nights} nuits). Total indicatif : ${money(stay+cfg.cleaningFee)}. Pouvez-vous confirmer la disponibilité et le tarif ?`;
 if(currentLang==='en')return `Hi! I would like to request a stay in Les Diablerets from ${dateFmt(arrivalDate)} to ${dateFmt(departureDate)} (${nights} nights). Estimated total: ${money(stay+cfg.cleaningFee)}. Could you confirm availability and the final rate?`;
 return `Ciao! Vorrei richiedere un soggiorno a Les Diablerets dal ${dateFmt(arrivalDate)} al ${dateFmt(departureDate)} (${nights} notti). Totale indicativo: ${money(stay+cfg.cleaningFee)}. Puoi confermare disponibilità e prezzo finale?`;
}
window.renderBookingCalendar=function(){
 const grid=document.getElementById('calendar-grid');if(!grid)return;
 const title=document.getElementById('calendar-title'),week=document.getElementById('calendar-weekdays');
 title.textContent=calendarMonth.toLocaleDateString(locale(),{month:'long',year:'numeric'});
 const weekdays=currentLang==='en'?['Mon','Tue','Wed','Thu','Fri','Sat','Sun']:currentLang==='fr'?['Lun','Mar','Mer','Jeu','Ven','Sam','Dim']:['Lun','Mar','Mer','Gio','Ven','Sab','Dom'];week.innerHTML=weekdays.map(x=>`<span>${x}</span>`).join('');grid.innerHTML='';
 const first=(calendarMonth.getDay()+6)%7,start=new Date(calendarMonth);start.setDate(1-first);const today=dayStart(new Date());
 for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const btn=document.createElement('button');btn.type='button';btn.className='calendar-day';btn.innerHTML=`<span>${d.getDate()}</span><small>${money(rateFor(d))}</small>`;if(d.getMonth()!==calendarMonth.getMonth())btn.classList.add('outside');if(d<today){btn.classList.add('past');btn.disabled=true}else if(isUnavailable(d)){btn.classList.add('unavailable');btn.disabled=true}else{btn.addEventListener('click',()=>selectCalendarDate(d))}if(arrivalDate&&iso(d)===iso(arrivalDate))btn.classList.add('selected');if(departureDate&&iso(d)===iso(departureDate))btn.classList.add('selected');if(arrivalDate&&departureDate&&d>arrivalDate&&d<departureDate)btn.classList.add('in-range');grid.appendChild(btn)}
 const fmt=d=>d?d.toLocaleDateString(locale(),{day:'2-digit',month:'short',year:'numeric'}):'—';document.getElementById('quote-arrival').textContent=fmt(arrivalDate);document.getElementById('quote-departure').textContent=fmt(departureDate);
 const cta=document.getElementById('booking-whatsapp');if(arrivalDate&&departureDate){const nights=Math.round((departureDate-arrivalDate)/86400000);let stay=0;for(let d=new Date(arrivalDate);d<departureDate;d.setDate(d.getDate()+1))stay+=rateFor(d);document.getElementById('quote-nights').textContent=nights;document.getElementById('quote-stay').textContent=money(stay);document.getElementById('quote-total').textContent=money(stay+cfg.cleaningFee);cta.classList.toggle('disabled',nights<cfg.minimumNights);cta.href=`https://wa.me/${PHONE}?text=${encodeURIComponent(bookingMessage())}`;cta.target='_blank';cta.rel='noopener'}else{document.getElementById('quote-nights').textContent='—';document.getElementById('quote-stay').textContent='—';document.getElementById('quote-total').textContent='—';cta.classList.add('disabled');cta.href='#'}
};
document.getElementById('calendar-prev')?.addEventListener('click',()=>{calendarMonth.setMonth(calendarMonth.getMonth()-1);renderBookingCalendar()});
document.getElementById('calendar-next')?.addEventListener('click',()=>{calendarMonth.setMonth(calendarMonth.getMonth()+1);renderBookingCalendar()});
document.getElementById('reset-dates')?.addEventListener('click',()=>{arrivalDate=null;departureDate=null;renderBookingCalendar()});
renderBookingCalendar();
